Reactor Netty HTTP Server Support
resteasy/resteasy-spring-boot pull request #169
Opened 2022-07-12 18:47 UTC by lalifk

### Purpose

This PR introduces support for [Reactor Netty HTTP Server](https://projectreactor.io/docs/netty/release/reference/index.html#http-server).

**Note:**
Code to provide a Reactor Netty server adapter needed for these changes was already contributed to Resteasy by @crankydillo. See [resteasy#2693](https://github.com/resteasy/resteasy/pull/2693).

### High level summary of changes
There are 3 important changes to highlight:

#### **1.** New project structure

For clarity and also in order to re-use as much code as possible, a new project structure is proposed in this PR.

**From**
```
resteasy-spring-boot-starter-parent
				|
				|__ resteasy-spring-boot-starter
				|
				|__ spring-boot-sample-app
				|
				|__ spring-boot-sample-app-for-wildfly
				|
				|__ spring-boot-sample-app-no-jaxrs-application
				|
				|__ resteasy-spring-boot-starter-test
```

**To**

```
resteasy-spring-boot-starter-parent
				\__ resteasy-spring-boot-starter-common-parent
				:	|
				:	|__ resteasy-spring-boot-starter-common
				:	|
				:	|__ resteasy-spring-boot-starter-sample-app-common
				|
				\__ resteasy-servet-spring-boot-starter-parent
				:	|
				:	|__ resteasy-servlet-spring-boot-starter
				:	|
				:	|__ resteasy-servlet-spring-boot-starter-test
				:	|
				:	|__ resteasy-servlet-spring-boot-sample-app
				:	|
				:	|__ resteasy-servlet-spring-boot-sample-app-no-jaxrs
				:	|
				:	|__ resteasy-wildfly-spring-boot-sample-app
				|
				\__ resteasy-reactor-netty-spring-boot-starter-parent
				 	|
				 	|__ resteasy-reactor-netty-spring-boot-starter
				 	|
				 	|__ resteasy-reactor-netty-spring-boot-starter-test
				 	|
				 	|__ resteasy-reactor-netty-spring-boot-sample-app
				 	|
				 	|__ resteasy-reactor-netty-spring-boot-sample-app-no-jaxrs

```

#### **2.** Code to support reactor Netty HTTP server in corresponding modules

####  **3.** READMEs updated to cover Reactor Netty HTTP server

2022-07-13 16:33 UTC, jamezp commented
I've got no strong opinion as I really don't know a lot about Spring or Spring Boot. At a glance I did see some tabs that may have crept in we should likely remove :)

2022-07-13 16:55 UTC, lalifk commented
> @lalifk Cool! In addition could you please fix the test error?
> 
I made another commit. Please try building again.

2022-07-13 17:35 UTC, liweinan requested changes

2022-07-13 17:35 UTC, liweinan commented on reactor-netty/resteasy-reactor-netty-spring-boot-starter/src/test/java/org/jboss/resteasy/springboot/JaxrsAppRegistrationTest.java
> +	@Test
needs some reformatting of the file

2022-07-13 17:35 UTC, liweinan commented on servlet/resteasy-servlet-spring-boot-sample-app-no-jaxrs/pom.xml
> +        <artifactId>resteasy-servet-spring-boot-starter-parent</artifactId>
here too

2022-07-13 17:35 UTC, liweinan commented on servlet/resteasy-servlet-spring-boot-sample-app/pom.xml
> +        <artifactId>resteasy-servet-spring-boot-starter-parent</artifactId>
I guess a global replacing would be fine.

2022-07-13 17:35 UTC, liweinan commented on servlet/pom.xml
> +    <artifactId>resteasy-servet-spring-boot-starter-parent</artifactId>
misspelling

2022-07-13 17:35 UTC, liweinan commented on servlet/resteasy-servlet-spring-boot-starter-test/pom.xml
> +        <artifactId>resteasy-servet-spring-boot-starter-parent</artifactId>
same here

2022-07-13 21:34 UTC, asoldano commented
> @lalifk In addition, we require all contributions to be made under the terms of the ASL 2.0 License:[ http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0)
> 
> Do you agree to these terms?

@liweinan , I believe @lalifk previously agreed with the license, see for example https://github.com/resteasy/Resteasy/pull/2242 .

2022-07-14 01:49 UTC, liweinan commented
@asoldano okay!

2022-07-14 03:55 UTC, lalifk commented
> @lalifk In addition, we require all contributions to be made under the terms of the ASL 2.0 License:[ http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0)
> 
> Do you agree to these terms?

I already did agree to those terms as pointed out by @asoldano.

2022-07-14 03:56 UTC, lalifk commented
> Could you please do a cleanup? Thanks!
Cleanup complete!

2022-07-14 14:32 UTC, merged